# Generated by Django 4.1.3 on 2023-01-14 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='dosen',
        ),
        migrations.RemoveField(
            model_name='post',
            name='kelas',
        ),
        migrations.RemoveField(
            model_name='post',
            name='mata_kuliah',
        ),
        migrations.AddField(
            model_name='post',
            name='harga',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='makanan',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Kelas',
        ),
    ]
