# Generated by Django 4.1.3 on 2023-01-14 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_post_dosen_remove_post_kelas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='gambar',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='harga',
            field=models.DecimalField(decimal_places=0, max_digits=6),
        ),
    ]
