# Generated by Django 4.1.3 on 2023-01-19 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_karyawan_pesanan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daftarmenu',
            name='makanan',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
